config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :comics, only: [:index, :show, :edit, :update, :create, :new, :destroy] do 
    resources :post_comments, only: [:create, :destroy]
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :story, presence: true
  validates :review, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :comic
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image
  
  has_many :comics, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  
  validates :name, presence: true,length: {minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] # top, about の2つのアクションのみ、ログイン無しでもアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
  
  def index
    @user = current_user
    
    @comics = Comic.page(params[:page]).reverse_order
  end

  def show
    @user = current_user
    
    @comic = Comic.find(params[:id])
    @comic_user = @comic.user
    
    @post_comment = PostComment.new
    
  end

  def new
    @comic = Comic.new
  end
  
  def create
    @user = current_user
    @comics = Comic.all
    @comic = Comic.new(comic_params)
    @comic.user_id = current_user.id
    if @comic.save
       redirect_to comic_path(@comic.id), notice: 'You have created book successfully.'
    else
    render :index
    end
  end 

  def edit
    @comic = Comic.find(params[:id])
  end
  
  def update
    @comic = Comic.find(params[:id])
    if @comic.update(comic_params)
    redirect_to comic_path(@comic.id),notice: 'You have updated book successfully.'
    else
      render :edit
    end
  end 
  
  def destroy
    comic = Comic.find(params[:id])
    comic.destroy
    redirect_to comics_path
  end 
  
   private
  
  def comic_params
    params.require(:comic).permit(:title, :story, :review, :user_id)
  end 
  
  def correct_user
    @comic= Comic.find(params[:id])
    @user = @comic.user
    redirect_to comics_path unless @user == current_user
  end 
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    comic = Comic.find(params[:comic_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.comic_id = comic.id
    comment.save
    redirect_to comic_path(comic)
  end 
  
  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to comic_path(params[:comic_id])
  end 
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @user = current_user
    @users = User.page(params[:page]).reverse_order
    @comic = Comic.new
  end

  def show
    @user = User.find(params[:id])
    
    @comics = @user.comics.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
  end
  
   def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path, notice: 'You have updated user successfully.'
    else
      render :edit
    end
   end
   
    private
  
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end 
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user.id) unless @user == current_user
  end 
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comics/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>投稿編集</h1>
        <% if @comic.errors.any? %>
          <h3><%= @comic.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
          <% @comic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
        
        <%= form_with model: @comic, local: true do |f|  %>
          <div class="form-group">
          　　<label for="comic_title">タイトル</label>
          　　　<%= f.text_field :title, id: "comic_title" %>
          </div>
          <div class="form-group">
          　　<labrl for="story">Oあらすじ・キーワード</labrl>
          　　<%= f.text_area :story, id: "story" %>
          </div>
          <div class="form-group">
          　　<label for="review">レビュー</label>
            　<%= f.text_area :review, id: "review" %>
          </div>
          <div class="form-group">
          　　<%= f.submit "編集", class: "btn btn-success" %>
          </div>
          
          <%= link_to 'Show', comic_path(@comic.id) %>
          <string>|</string>
          <%= link_to 'Back', comics_path %>
        　　　　<% end %>
      </div>
    </div>
  </div>
</main>

app/views/comics/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'sidebar/userinfo', user: @user %>
      <div class='right col-md-8 offset-md-1'>
        <h2>Comics</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>タイトル</th>
              <th>あらすじ</th>
              <th>レビュー</th>
              <th colspan="4"></th>
            </tr>
            <% @comics.each do |comic| %>
            <tr>
              <td>
                <%= link_to user_path(comic.user.id) do %>
                  <%= attachment_image_tag comic.user, :profile_image, size: "100x100", fallback: "default-image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to comic.title, comic_path(comic.id) %></td>
              <td><%= comic.story %></td>
              <td><%= comic.review %></td>
            </tr>
            <% end %>
          </thead>
          <tbody></tbody>
        </table>
        
        <div class="paginate">
       　　 <%= paginate @comics %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/comics/new.html.erb
<main>
  <div class="container">
    <% if @comic.errors.any? %>
      <div class="row">
      　　<h3><%= @comic.errors.count %>errors prohibited this obj from being saved:</h3>
      </div>
      <div class="row">
      　　<ul>
      　　　　<% @comic.errors.full_messages.each do |message| %>
      　　　　<li><%= message %></li>
      　　　　<% end %>
      　　</ul>
      </div>
  　<% end %>
    　<div class="row">
      　　<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        　　　　<div class="new">
        　　　　　　　　<h1>新規投稿</h1>
       　　　　　　　　　　 <%= form_with model: @comic, local: true do |f|  %>
          　　　　　　<div class="form-group">
          　　　　　　　　　　<label for="book_title">タイトル</label>
          　　　　　　　　　　　　　　<div>
         　　　　　　　　　　　　　　　　　　　<%= f.text_area :title, rows:'1', cols: '60', id: "inputTitle" %>
          　　　　　　　　　　　　　　</div>
          　　　　　　</div>
          　　　　　　<div class="form-group">
          　　　　　　　　　　<label for="story">あらすじ・キーワード</label>
          　　　　　　　　　　　　　　<div>
          　　　　　　　　　　　　　　　　　　<%= f.text_area :story, rows:'3', cols: '60', id: "inputStory" %>
          　　　　　　　　　　　　　　</div>
          　　　　　　　</div>
          　　　　　　<div class="form-group">
          　　　　　　　　　　<label for="review">レビュー</label>
            　　　　　　　　　　　　<div>
            　　　　　　　　　　　　　　　　<%= f.text_area :review, rows:'3', cols: '60', id: "inputReview" %>
            　　　　　　　　　　　　</div>
          　　　　　　　</div>
          　　　　　　<div class="form-group">
          　　　　　　　　　　<%= f.submit "投稿", class: "btn btn-success" %>
          　　　　　　</div>
          
          　　　　　　<%= link_to 'Back', comics_path %>
        　　　　　　　　<% end %>
       　　　　　 </div>
      　　</div>
    　</div>
  </div>
</main>

app/views/comics/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'sidebar/userinfo', user: @comic_user %>
        <div class='col-md-8 offset-md-1'>
          <h2>Comic detail</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <td>
                <%= link_to user_path(@comic_user.id) do %>
                  <%= attachment_image_tag @comic_user, :profile_image, size: "100x100", fallback: "default-image.jpg" %>
                <% end %><br>
                <%= link_to @comic_user.name, user_path(@comic_user.id) %>
              </td>
              <td><%= link_to @comic.title, comic_path(@comic.id) %></td>
              <td><%= @comic.story %></td>
              <td><%= @comic.review %></td>
              <% if @comic_user.id == current_user.id %>
              <td><%= link_to 'Edit', edit_comic_path(@comic.id) %></td>
              <td><%= link_to 'Destroy', comic_path(@comic.id), method: :delete, "data-confirm" => "本当に消しますか？"%></td>
              <% end %>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
        
        <div class='comment'>
          <h2>コメント</h2>
            <%= form_with(model:[@comic, @post_comment], local: true) do |f| %>
            <%= f.text_area :comment, rows:'3', cols: '60', placeholder: "コメントをここに" %>
            <%= f.submit "送信する" %>
            <% end %>
        </div>
        
        <table class='table table-hover table-inverse table-borderless'>
          <h2>コメント一覧</h2>
            <p>コメント件数：<%= @comic.post_comments.count %></p>
              <% @comic.post_comments.each do |post_comment| %>
          <thead>
            <tr>
              <th></th>
              <td>
                <p><%= attachment_image_tag post_comment.user, :profile_image, size: "100x100", fallback: "default-image.jpg" %></p>
                <%= post_comment.user.name %>
              </td>
              <td><%= post_comment.comment %></td>
              <td><%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
              <% if post_comment.user == current_user %>
              <td><%= link_to "削除", comic_post_comment_path(post_comment.comic, post_comment), method: :delete %> </td>
              <% end %>
              <% end %>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody></tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div>
    <div>
      <h1 class="about mx-5">セコミックスにようこそ！</h2>
    </div>
    <div class="onepiece">
      <%= image_tag 'onepiece02_zoro_bandana.png'%> <%= image_tag 'onepiece01_luffy.png' %> <%= image_tag 'onepiece03_nami.png' %>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='m-auto p-auto col-11 col-sm-10 col-lg-8 col-xl-12'>
        <h1 class="top">セコミックスへようこそ!!</h1>
        <p class="top2">セコミックスではネット漫画の情報やおすすめを知ることができます</p>
        <div class="btn-wrapper col-6 mx-auto">
          <div class="top-btn">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Secomics</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <a class="nav-link text-light" href="/users/<%= current_user.id %>">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/comics">
              <i class="fas fa-book-open"></i>Comics
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secomics1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/sidebar/_userinfo.html.erb
<div class='col-md-3'>
        <h2>User info</h2>
        <table class='table'>
          <tr>
            <%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "default-image.jpg" %>
          </tr>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </table>　 
        <div class='row'>
          <%= link_to edit_user_path(user.id), class: "btn btn-outline-dark btn-block"  do %>
            <i class="fas fa-user-cog"></i>
            <% end %>
        </div>
        
        <h2 class="mt-5 mx-5">新規投稿は<br>
                         こちらから</h2>
          <div class="form-group-new">
            <%= link_to '新規投稿', new_comic_path, class: "btn btn-warning" %>
          </div>
      </div>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <div class="edit">
        <h1>User info</h1>
        <% if @user.errors.any? %>
          <h3><%= @user.errors.count %>errors prohibited this obj from being saved:</h3>
          <ul>
           <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
          </ul>
        <% end %>
        
        <%= form_with model:@user, local: true do |f| %>
          <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, id: "inputName" %>
          </div>
          <div class="form-group">
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image %>
          </div>
          <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, id: "inputIntroduction" %>
          </div>
          <div class="form-group">
          <%= f.submit "編集", class: "btn btn-secondary" %>
          </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
      <%= render 'sidebar/userinfo', user: @user, comic: @comic %>
      <div class='right col-md-8 offset-md-1'>
        <h2>Users</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>画像</th>
              <th>名前</th>
              <th></th>
              <th colspan="3"></th>
            </tr>
            <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "default-image.jpg" %></td>
              <td><%= user.name %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
            </tr>
            <% end %>
          </thead>
          <tbody></tbody>
        </table>
        <div class="paginate">
          <%= paginate @users %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container px-5 px-sm-0'>
    <div class='row'>
       <%= render 'sidebar/userinfo', user: @user, comic: @comic %>
      <div class='col-md-8 offset-md-1'>
        <h2>Comics</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>タイトル</th>
              <th>あらすじ</th>
              <th>レビュー</th>
              <th colspan="4"></th>
            </tr>
            <% @comics.each do |comic_user| %>
            <tr>
              <td>
                <%= link_to user_path(@user.id) do %>
                    <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "default-image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to comic_user.title, comic_path(comic_user.id) %></td>
              <td><%= comic_user.story %></td>
              <td><%= comic_user.review %></td>
            </tr>
            <% end %>
          </thead>
          <tbody></tbody>
        </table>
        <div class="paginate">
          <%= paginate @comics %>
        </div>
      </div>
    </div>
  </div>
</main>